services:
  crumb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE: ecto://postgres:postgres@db:5432/crumb_prod
      USERNAME: postgres
      PASSWORD: postgres
      SECRET_KEY_BASE: a_very_secret_key_that_you_generate
      PHX_HOST: localhost
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crumb_prod
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
